name: "invoked.net"

url: 'https://moribellamy.github.io'

# Comment out in devel:
baseurl: /_site/

markdown: kramdown
markdown_ext: "md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year-:month-:day-:title/

source: .
destination: ./_site
